*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 12.07.2021 at 22:15:08
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZYKZ_C_WF_DM_USR................................*
FORM GET_DATA_ZYKZ_C_WF_DM_USR.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZYKZ_WF_DEMO_USR WHERE
(VIM_WHERETAB) .
    CLEAR ZYKZ_C_WF_DM_USR .
ZYKZ_C_WF_DM_USR-MANDT =
ZYKZ_WF_DEMO_USR-MANDT .
ZYKZ_C_WF_DM_USR-USERNAME =
ZYKZ_WF_DEMO_USR-USERNAME .
<VIM_TOTAL_STRUC> = ZYKZ_C_WF_DM_USR.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZYKZ_C_WF_DM_USR .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZYKZ_C_WF_DM_USR.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZYKZ_C_WF_DM_USR-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZYKZ_WF_DEMO_USR WHERE
  USERNAME = ZYKZ_C_WF_DM_USR-USERNAME .
    IF SY-SUBRC = 0.
    DELETE ZYKZ_WF_DEMO_USR .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZYKZ_WF_DEMO_USR WHERE
  USERNAME = ZYKZ_C_WF_DM_USR-USERNAME .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZYKZ_WF_DEMO_USR.
    ENDIF.
ZYKZ_WF_DEMO_USR-MANDT =
ZYKZ_C_WF_DM_USR-MANDT .
ZYKZ_WF_DEMO_USR-USERNAME =
ZYKZ_C_WF_DM_USR-USERNAME .
    IF SY-SUBRC = 0.
    UPDATE ZYKZ_WF_DEMO_USR ##WARN_OK.
    ELSE.
    INSERT ZYKZ_WF_DEMO_USR .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZYKZ_C_WF_DM_USR-UPD_FLAG,
STATUS_ZYKZ_C_WF_DM_USR-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZYKZ_C_WF_DM_USR.
  SELECT SINGLE * FROM ZYKZ_WF_DEMO_USR WHERE
USERNAME = ZYKZ_C_WF_DM_USR-USERNAME .
ZYKZ_C_WF_DM_USR-MANDT =
ZYKZ_WF_DEMO_USR-MANDT .
ZYKZ_C_WF_DM_USR-USERNAME =
ZYKZ_WF_DEMO_USR-USERNAME .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZYKZ_C_WF_DM_USR USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZYKZ_C_WF_DM_USR-USERNAME TO
ZYKZ_WF_DEMO_USR-USERNAME .
MOVE ZYKZ_C_WF_DM_USR-MANDT TO
ZYKZ_WF_DEMO_USR-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZYKZ_WF_DEMO_USR'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZYKZ_WF_DEMO_USR TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZYKZ_WF_DEMO_USR'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
